# START_FEATURE pre_commit
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.8
exclude: /migrations/
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-merge-conflict
  - id: check-added-large-files
- repo: https://gitlab.com/PyCQA/flake8
    rev: 3.9.0
    hooks:
    -   id: flake8
        types: [file, python]
        args: ['--config=config/setup.cfg']
- repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
    -   id: isort
        types: [file, python]
# END_FEATURE pre_commit
