# Generated by Django 5.2.12 on 2026-03-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='sample_object',
        ),
        migrations.AddField(
            model_name='attachment',
            name='sample_object',
            field=models.ManyToManyField(related_name='attachments', to='app.sampleobject'),
        ),
    ]
