# Generated by Django 5.2.12 on 2026-03-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_attachment_sample_object_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='sample_object',
        ),
        migrations.AddField(
            model_name='sampleobject',
            name='attachments',
            field=models.ManyToManyField(related_name='sample_objects', to='app.attachment'),
        ),
    ]
