# Generated by Django 5.2.12 on 2026-03-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_attachment_sample_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='deleted_on',
            field=models.DateTimeField(null=True),
        ),
    ]
