settings:
  aws:autoscaling:asg:
    Availability Zones: Any
    Cooldown: '360'
    Custom Availability Zones: ''
    EnableCapacityRebalancing: 'false'
    MaxSize: '1'
    MinSize: '1'
  aws:autoscaling:launchconfiguration:
    BlockDeviceMappings: null
    DisableIMDSv1: 'true'
    EC2KeyName: null
    IamInstanceProfile: aws-elasticbeanstalk-ec2-role
    InstanceType: t3.small
    LaunchTemplateTagPropagationEnabled: null
    MonitoringInterval: 5 minute
    RootVolumeIOPS: null
    RootVolumeSize: null
    RootVolumeThroughput: null
    RootVolumeType: null
    SSHSourceRestriction: tcp,22,22,0.0.0.0/0
    SecurityGroups: # emily todo
  aws:autoscaling:updatepolicy:rollingupdate:
    MaxBatchSize: null
    MinInstancesInService: null
    PauseTime: null
    RollingUpdateEnabled: 'false'
    RollingUpdateType: Time
    Timeout: PT30M
  aws:ec2:instances:
    EnableSpot: 'false'
    InstanceTypes: t3.small
    SpotFleetOnDemandAboveBasePercentage: '0'
    SpotFleetOnDemandBase: '0'
    SpotMaxPrice: null
    SupportedArchitectures: x86_64
  aws:ec2:vpc:
    AssociatePublicIpAddress: 'false'
    ELBScheme: public
    ELBSubnets: # emily todo
    Subnets: # emily todo
    VPCId: # emily todo
  aws:elasticbeanstalk:application:
    Application Healthcheck URL: /health-check/
  aws:elasticbeanstalk:cloudwatch:logs:
    DeleteOnTerminate: 'false'
    RetentionInDays: '7'
    StreamLogs: 'false'
  aws:elasticbeanstalk:cloudwatch:logs:health:
    DeleteOnTerminate: 'false'
    HealthStreamingEnabled: 'false'
    RetentionInDays: '7'
  aws:elasticbeanstalk:command:
    BatchSize: '100'
    BatchSizeType: Percentage
    DeploymentPolicy: AllAtOnce
    IgnoreHealthCheck: 'false'
    Timeout: '600'
  aws:elasticbeanstalk:container:python:
    NumProcesses: '1'
    NumThreads: '15'
  aws:elasticbeanstalk:control:
    DefaultSSHPort: '22'
    LaunchTimeout: '0'
    LaunchType: Migration
    RollbackLaunchOnFailure: 'false'
  aws:elasticbeanstalk:environment:
    EnvironmentType: SingleInstance
    ExternalExtensionsS3Bucket: null
    ExternalExtensionsS3Key: null
    ServiceRole: # emily todo
  aws:elasticbeanstalk:environment:proxy:
    ProxyServer: apache
  aws:elasticbeanstalk:environment:proxy:staticfiles:
    /static: staticfiles
  aws:elasticbeanstalk:healthreporting:system:
    ConfigDocument: '{"Version":1,"CloudWatchMetrics":{"Instance":{"RootFilesystemUtil":null,"CPUIrq":null,"LoadAverage5min":null,"ApplicationRequests5xx":null,"ApplicationRequests4xx":null,"CPUUser":null,"LoadAverage1min":null,"ApplicationLatencyP50":null,"CPUIdle":null,"InstanceHealth":null,"ApplicationLatencyP95":null,"ApplicationLatencyP85":null,"ApplicationLatencyP90":null,"CPUSystem":null,"ApplicationLatencyP75":null,"CPUSoftirq":null,"ApplicationLatencyP10":null,"ApplicationLatencyP99":null,"ApplicationRequestsTotal":null,"ApplicationLatencyP99.9":null,"ApplicationRequests3xx":null,"ApplicationRequests2xx":null,"CPUIowait":null,"CPUNice":null},"Environment":{"InstancesSevere":null,"InstancesDegraded":null,"ApplicationRequests5xx":null,"ApplicationRequests4xx":null,"ApplicationLatencyP50":null,"ApplicationLatencyP95":null,"ApplicationLatencyP85":null,"InstancesUnknown":null,"ApplicationLatencyP90":null,"InstancesInfo":null,"InstancesPending":null,"ApplicationLatencyP75":null,"ApplicationLatencyP10":null,"ApplicationLatencyP99":null,"ApplicationRequestsTotal":null,"InstancesNoData":null,"ApplicationLatencyP99.9":null,"ApplicationRequests3xx":null,"ApplicationRequests2xx":null,"InstancesOk":null,"InstancesWarning":null}},"Rules":{"Environment":{"ELB":{"ELBRequests4xx":{"Enabled":true}},"Application":{"ApplicationRequests4xx":{"Enabled":true}}}}}'
    EnhancedHealthAuthEnabled: 'true'
    HealthCheckSuccessThreshold: Ok
    SystemType: enhanced
  aws:elasticbeanstalk:hostmanager:
    LogPublicationControl: 'false'
  aws:elasticbeanstalk:managedactions:
    ManagedActionsEnabled: 'true'
    PreferredStartTime: SAT:12:00
    ServiceRoleForManagedUpdates: # emily todo
  aws:elasticbeanstalk:managedactions:platformupdate:
    InstanceRefreshEnabled: 'false'
    UpdateLevel: minor
  aws:elasticbeanstalk:monitoring:
    Automatically Terminate Unhealthy Instances: 'true'
  aws:elasticbeanstalk:sns:topics:
    Notification Endpoint: null
    Notification Protocol: email
    Notification Topic ARN: null
    Notification Topic Name: null
  aws:elasticbeanstalk:sqsd:
    ConnectTimeout: '5'
    ErrorVisibilityTimeout: null
    HttpConnections: '50'
    HttpPath: /tasks/run_task
    InactivityTimeout: '6000'
    MaxRetries: '1'
    MimeType: application/json
    RetentionPeriod: '345600'
    VisibilityTimeout: '300'
    WorkerQueueURL: null
  aws:elasticbeanstalk:trafficsplitting:
    EvaluationTime: null
    NewVersionPercent: null
  aws:elasticbeanstalk:xray:
    XRayEnabled: 'false'
  aws:rds:dbinstance:
    HasCoupledDatabase: 'false'
