
name: Deploy

on:
  workflow_dispatch:
    inputs:
      services:
        description: "ECS Services to deploy"
        required: true
        default: "web worker"

      environment:
        type: choice
        description: Deploy Environment
        default: test
        options:
          - prod
          - test

      branch:
        description: Branch to build

      migration:
        type: boolean
        description: "Run migrations?"
        default: true

      build:
        type: boolean
        description: "Build new image?"
        default: true

permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy-${{ inputs.environment }}-${{ inputs.branch }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy (${{ inputs.branch }} onto ${{ inputs.environment }})
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}

      - name: Configure AWS CLI profile
        shell: bash
        run: |
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }} --profile ${{ vars.AWS_PROFILE_NAME }}
          aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }} --profile ${{ vars.AWS_PROFILE_NAME }}
          aws configure set aws_session_token ${{ env.AWS_SESSION_TOKEN }} --profile ${{ vars.AWS_PROFILE_NAME }}
          aws configure set region us-east-1 --profile ${{ vars.AWS_PROFILE_NAME }}

      - name: Check Profile
        shell: bash
        run: aws sts get-caller-identity --profile ${{ vars.AWS_PROFILE_NAME }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.3
          terraform_wrapper: false

      - name: Set up Docker Buildx builder
        shell: bash
        run: |
          docker buildx create --name containerd-builder --driver docker-container --use || true
          docker buildx inspect --bootstrap

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ACTIONS_SSH_KEY }}

      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Copy default .env file
        working-directory: config
        run: cp .env.build .env

      - name: Terraform init
        shell: bash
        working-directory: ./terraform/deployments/${{ inputs.environment }}
        env:
          AWS_PROFILE: ${{ vars.AWS_PROFILE_NAME }}
        run: |
          terraform init

      - name: Deploy application
        run: |
          uv run deploy ${{ inputs.environment }} run-deployment \
              --branch ${{ inputs.branch }} \
              ${{ inputs.migration && '' || '--no-migration' }} \
              ${{ inputs.build && '' || '--no-build' }}
